from abutionpy.abution_aggregator import Aggregators
from abutionpy.abution_schema import Schema, Dimension, T, Agg

def get_knowlion_schema(monitor: Aggregators = Agg.FloatArrayAdd()):
        return (Schema.Builder()
                  .entity("Metadata", Dimension.label("Metadata", "知识库信息 - 内存热数据")
                          .property("knowlion_info", T.CustomMap, Agg.CustomMap(Agg.Last()), "存知识库信息等")
                          .property("classify_map", T.CustomMap, Agg.CustomMap(Agg.Last()), "存classify的中英文映射")
                          .groupBy()
                          .build())
                  .entity("文档", Dimension.label("Doc", "文档向量索引+BM25存储")
                          .property("titles", T.TreeSetString, Agg.CollectionConcat(), "原文目录/标题列表")
                          .property("vector", T.VectorIndex, Agg.VectorIndexMerge(), "段落向量索引，key为段落的主题名，value为段落属性content的向量")
                          .property("doc_bm25", T.BM25Index, Agg.BM25Index(), "实体词频统计")
                          .property("user_id", T.String, Agg.Last(), "用户ID")
                          .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                          .property("updated_at", T.Long, Agg.Max(), "更新时间")
                          .groupBy("user_id", "classify")
                          .build())
                  .entity("段落", Dimension.label("Para", "文本段落")
                          .property("doc_name", T.TreeSetString, Agg.CollectionConcat(), "所属文章名 - 如果段落出现合并则集合为两个合并段落的文档名")
                          .property("content", T.String, Agg.StrConcat("\n"), "段落内容")
                          .property("type", T.String, Agg.StrConcat("|"), "类型（Text、Code、Table、Image、Formulas）")
                          .property("entity_count", T.Integer, Agg.Sum(), "段落中实体数量")
                          .property("vector", T.FloatArray, Agg.FloatArrayAdd(), "段落语义向量")
                          .property("processing", T.Boolean, Agg.IsTrue(), "段落处理-执行Agent的状态控制")
                          .property("user_id", T.String, Agg.Last(), "用户ID")
                          .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                          .groupBy("user_id", "classify", "doc_name")
                          .build())
                  .entity("实体", Dimension.label("Entity", "段落中的实体")
                          .property("labels", T.TreeSetString, Agg.CollectionConcat(), "实体标签集合 - 已用于BM25中")
                          .property("synonyms", T.TreeSetString, Agg.CollectionConcat(), "实体同义词合集 - 已用于BM25中")
                          .property("details", T.CustomMap, Agg.CustomMap(Agg.StrConcat("\n")), "实体描述：聚合段落的内容，key为段落主题名，value为实体描述Set集合；同时可用于计算节实体HLL-出现在多少个段落中")
                          .property("occur_count", T.Integer, Agg.Sum(), "实体出现频率 - 按段落算每次+1")
                          .property("confidence", T.QuantileDoubles, Agg.QuantileDoubles(), "（置信度评分取值：[0-1]）")
                          .property("importance", T.QuantileDoubles, Agg.QuantileDoubles(), "（重要性评分取值：[0-1]）")
                          .property("neighbors", T.DistinctCountHllp, Agg.DistinctCountHllp(), "邻居数-高基数统计")
                          .property("vector", T.FloatArray, Agg.FloatArrayAdd(), "邻居聚合向量字段 - 存所有同名实体信息与邻居信息的综合向量（自动语义聚合）")
                          .property("vector_paras", T.CustomMap, Agg.CustomMap(monitor), "段落与向量的映射，内部聚合函数VectorCrudAgent触发条件为相似度阈值，并配置执行的大模型参数")
                          .property("user_id", T.String, Agg.Last(), "用户ID")
                          .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                          .groupBy("user_id", "classify")
                          .build())
                  .edge("文档", "段落", Dimension.label("Doc2Para", "文档关联段落主题")
                        .property("user_id", T.String, Agg.Last(), "用户ID")
                        .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                        .groupBy("user_id", "classify")
                        .build())
                  .edge("段落", "段落", Dimension.label("Para2Para", "章节中段落上下文关系 - 只记录了切片内上下文，切片间因并行处理无法处理，重叠区域有可能会弥补，但不绝对）")
                        .property("occur_count", T.Integer, Agg.Sum(), "关系出现频率 - 按段落算每次+1")
                        .property("user_id", T.String, Agg.Last(), "用户ID")
                        .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                        .groupBy("user_id", "classify")
                        .build())
                  .edge("段落", "实体", Dimension.label("Para2Entity", "段落中的实体")
                        .property("user_id", T.String, Agg.Last(), "用户ID")
                        .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                        .groupBy("user_id", "classify")
                        .build())
                  .edge("实体", "实体", Dimension.label("Entity2Entity", "段落中实体间的联系")
                        .property("fact", T.TreeSet, Agg.CollectionConcat(), "关系事实描述")
                        .property("occur_count", T.Integer, Agg.Sum(), "实体出现频率 - 每次+1")
                        .property("user_id", T.String, Agg.Last(), "用户ID")
                        .property("classify", T.String, Agg.StrConcat("|"), "文档分类-英文（用于可见性标签）")
                        .groupBy("user_id", "classify")
                        .build())
                  # 可见性字段配置
                  .dataRoleProperty("classify")
                  .build())
